name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Deploy Frontend
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: 'src/frontend'
          acrName: icdregistry
          acrUsername: ${{ secrets.AZURE_USERNAME }}
          acrPassword: ${{ secrets.AZURE_PASSWORD }}
          containerAppName: ca-quotes
          resourceGroup: icd
          containerAppEnvironment: my-test-container-app-env
          
      - name: Build and Deploy Quote Service
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: 'src/backend/QuoteService'
          acrName: icdregistry
          acrUsername: ${{ secrets.AZURE_USERNAME }}
          acrPassword: ${{ secrets.AZURE_PASSWORD }}
          containerAppName: ca-quotes
          resourceGroup: icd
          containerAppEnvironment: my-test-container-app-env